theme = "tokyonight_storm"

[editor]
scrolloff = 15
mouse = true
line-number = "absolute"
cursorline = true
# gutters = ["diagnostics", "spacer", "diff"]
auto-completion = true
auto-format = true
true-color = true
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-modification-indicator", "file-name"]
right = ["version-control", "diagnostics", "file-type"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
