theme = 'tokyonight'

[editor]
mouse = true
cursorline = true
gutters = ["diagnostics", "spacer", "diff"]
auto-completion = true
auto-format = true
true-color = true
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.normal]
esc=["collapse_selection", "keep_primary_selection"]
